name: Deploy to Nhost

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nhost CLI
        uses: nhost-actions/install-nhost-cli@v1

      - name: Authenticate with Nhost
        uses: nhost-actions/authenticate@v1
        with:
          pat: ${{ secrets.NHOST_PAT }}

      - name: Deploy to Nhost
        uses: nhost-actions/deploy@v1
        with:
          subdomain: qhdhzninoxahvtvpaytg